name: scanpy_qc
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::python=3.10.12
  - r-base=4.2
  - r-essentials
  - conda-forge::scanpy
  - conda-forge::papermill
  - conda-forge::ipykernel=6.29.3
  - conda-forge::notebook
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::anndata
  - conda-forge::seaborn
  - conda-forge::matplotlib
  - conda-forge::rpy2
  - bioconda::pyensembl
  - conda-forge::r-clustree
  - conda-forge::r-ggplot2
  - conda-forge::r-cairo
  - conda-forge::scikit-learn
  - conda-forge::numcodecs
  - conda-forge::jupyterlab
  #- conda-forge::jupyterlab_widgets
  #- conda-forge::ipywidgets
  #- conda-forge::widgetsnbextension
  - conda-forge::ipython
  - conda-forge::poppler
  - conda-forge::pip
  - pip:
    - scimap
    - datacache
    - singler
    - celldex
    - harmonypy
    - pdf2image