name: scanpy_qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.12
  - conda-forge::scanpy=1.10.1
  - conda-forge::papermill=2.5.0
  - conda-forge::ipykernel=6.29.3
  - conda-forge::notebook=7.1.3
